# Analysis notebook

## 1- running the functions useful for this

In [1]:
%run function_analysis.ipynb

c:\Users\Elise\anaconda3\envs\Dissertation_2.0\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Versions:
pandas:  3.0.3
torch:  2.7.1+cpu
transformers:  4.52.4
spacy:  3.8.14
geopy:  2.5.0

Device set to use cpu

## 2- reading the current datafile

In [2]:
current_data = pd.read_csv("current_dataset.csv")
current_full_data = pd.read_csv("current_full_dataset_v2.csv")

In [3]:
# making a copy of the dataframe
current_data_copy = current_data.copy()
current_full_data_copy = current_full_data.copy()

In [4]:
# changing the column types of theme and country
current_data_copy["theme"] = current_data_copy["theme"].astype(object)
current_data_copy["country"] = current_data_copy["country"].astype(object)

In [5]:
# getting the data that has not been analysed yet
to_merge_data = current_data_copy[["url", "title", "authors", "date", "extract"]]
to_merge_full_data = current_full_data_copy[["url", "title", "authors", "date", "extract"]]
merged_data = to_merge_data.merge(to_merge_full_data, how='left', indicator=True)

In [6]:
data_to_analyse =  current_data_copy[merged_data["_merge"] == "left_only"]
data_to_analyse

,url,title,authors,date,extract,country,theme
780,https://africabrief.substack.com/p/new-action-...,New Action Plan Offers Hope for People With Al...,Steria Manda,"Jul 23, 2026","The need for urgent action, he said, has been ...",NaN,NaN
781,https://www.world-today-news.com/malawis-new-a...,Malawi’s New Action Plan Aims to End Economic ...,NaN,NaN,"The plan, developed with input from Human Righ...",NaN,NaN
782,https://www.nyasatimes.com/persons-with-albini...,Persons with albinism plead for skills trainin...,NaN,NaN,"As you might be aware, most of us are economic...",NaN,NaN
783,https://www.nyasatimes.com/persons-with-albini...,Persons with albinism plead for skills trainin...,NaN,NaN,"Speaking in separate interview, Maguba – who i...",NaN,NaN
784,https://africaalbinismnetwork.org/wp-content/u...,Submission in response to the call for inputs:...,Africa Albinism Network,NaN,"I was once asked “you barely see, why are you ...",NaN,NaN
785,https://africaalbinismnetwork.org/wp-content/u...,Submission in response to the call for inputs:...,Africa Albinism Network,NaN,"In one instance, a school's rules required all...",NaN,NaN
786,https://africaalbinismnetwork.org/wp-content/u...,Submission in response to the call for inputs:...,Africa Albinism Network,NaN,Students with albinism encounter significant h...,NaN,NaN
787,https://www.intechopen.com/online-first/1236046,Bullying and Exclusion of Children with Albini...,"Margit Stein, Stefanie Kleine Bornhorst, Felis...",12 November 2025,The model school for inclusive education prese...,NaN,NaN
788,https://link.springer.com/article/10.1186/s129...,Children with albinism in African regions: the...,"Anita Franklin, Patricia Lund, Caroline Bradbu...",12 January 2018,"When I was at primary school, people used to l...",NaN,NaN
789,https://link.springer.com/article/10.1186/s129...,Children with albinism in African regions: the...,"Anita Franklin, Patricia Lund, Caroline Bradbu...",12 January 2018,People used to abuse me on the road when I too...,NaN,NaN
790,https://link.springer.com/article/10.1186/s129...,Children with albinism in African regions: the...,"Anita Franklin, Patricia Lund, Caroline Bradbu...",12 January 2018,They would run after me - crowds of kids follo...,NaN,NaN
791,https://doi.org/10.38140/ijspsy.v3i1.901,Exploring barriers to learning hindering Learn...,Margaret Machingambi,2023-08-28,"""My peers in my class do not want to walk with...",NaN,NaN
792,https://doi.org/10.38140/ijspsy.v3i1.901,Exploring barriers to learning hindering Learn...,Margaret Machingambi,2023-08-28,"""My peers without albinism used to say abusive...",NaN,NaN
793,https://doi.org/10.38140/ijspsy.v3i1.901,Exploring barriers to learning hindering Learn...,Margaret Machingambi,2023-08-28,"""My English teacher ignores me if I complain t...",NaN,NaN

## 3- loading the places that have already been mapped

In [7]:
with open("place_country.json", "r", encoding="utf-8") as f:
    map_dic = json.load(f)

## 4- doing the analysis

In [8]:
new_full_data, new_map_dic = analyse(data_to_analyse, map_dic=map_dic)

--------------------
analysing line 0
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 1 identified
Extracting places names
2 places identified, extracting country names
New place, using geopy
Place was already mapped
found 2 countries
--------------------
analysing line 1
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
0 places identified, extracting country names
found 0 countries
--------------------
analysing line 2
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 1 identified
Extracting places names
0 places identified, extracting country names
found 0 countries
--------------------
analysing line 3
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 1 identified
Extracting places names
2 places identified, extracting country names
New place, using geopy
New place, using geopy
found 2 countries
--------------------
analysing line 4
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
0 places identified, extracting country names
found 0 countries
--------------------
analysing line 5
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
0 places identified, extracting country names
found 0 countries
--------------------
analysing line 6
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 1 identified
Extracting places names
0 places identified, extracting country names
found 0 countries
--------------------
analysing line 7
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
1 places identified, extracting country names
Place was already mapped
found 1 countries
--------------------
analysing line 8
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
0 places identified, extracting country names
found 0 countries
--------------------
analysing line 9
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
0 places identified, extracting country names
found 0 countries
--------------------
analysing line 10
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
2 places identified, extracting country names
New place, using geopy
Place was already mapped
found 1 countries
--------------------
analysing line 11
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
1 places identified, extracting country names
Place was already mapped
found 1 countries
--------------------
analysing line 12
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 0 identified
Extracting places names
1 places identified, extracting country names
Place was already mapped
found 1 countries
--------------------
analysing line 13
--------------------
--------------------
Starting zero-shot classification
--------------------
Classification succeeded, 1 identified
Extracting places names
1 places identified, extracting country names
Place was already mapped
found 1 countries

## 5- saving the dataset with the analyses

In [9]:
current_full_data = pd.concat([current_full_data_copy, new_full_data], ignore_index=True)

In [10]:
current_full_data.to_csv("current_full_dataset_v2.csv", index=False)

In [11]:
current_full_data

,index,url,title,authors,date,extract,country,theme
0,0,https://theconversation.com/attacks-on-people-...,Attacks on people with albinism in Tanzania: A...,Charlotte Baker,NaN,"Most recently, on 25 June 2024, a two-year-old...",['Tanzania'],['right to life']
1,1,https://digitalcommons.wcl.american.edu/cgi/vi...,The Witchcraft Act and the Cost of Inaction: A...,Aly Orvis,2025,"On February 5, 2025, the African Court on Huma...",['Tanzania'],[]
2,2,https://digitalcommons.wcl.american.edu/cgi/vi...,The Witchcraft Act and the Cost of Inaction: A...,Aly Orvis,2025,This belief has fueled long-term and widesprea...,[],['right to life']
3,3,https://digitalcommons.wcl.american.edu/cgi/vi...,The Witchcraft Act and the Cost of Inaction: A...,Aly Orvis,2025,"In some instances, even the graves of deceased...",[],[]
4,4,https://digitalcommons.wcl.american.edu/cgi/vi...,The Witchcraft Act and the Cost of Inaction: A...,Aly Orvis,2025,The Applicants presented testimony from victim...,[],[]
...,...,...,...,...,...,...,...,...
789,789,https://link.springer.com/article/10.1186/s129...,Children with albinism in African regions: the...,"Anita Franklin, Patricia Lund, Caroline Bradbu...",12 January 2018,People used to abuse me on the road when I too...,[],[]
790,790,https://link.springer.com/article/10.1186/s129...,Children with albinism in African regions: the...,"Anita Franklin, Patricia Lund, Caroline Bradbu...",12 January 2018,They would run after me - crowds of kids follo...,[Hrvatska],[]
791,791,https://doi.org/10.38140/ijspsy.v3i1.901,Exploring barriers to learning hindering Learn...,Margaret Machingambi,2023-08-28,"""My peers in my class do not want to walk with...",[Zimbabwe],[]
792,792,https://doi.org/10.38140/ijspsy.v3i1.901,Exploring barriers to learning hindering Learn...,Margaret Machingambi,2023-08-28,"""My peers without albinism used to say abusive...",[Zimbabwe],[]
793,793,https://doi.org/10.38140/ijspsy.v3i1.901,Exploring barriers to learning hindering Learn...,Margaret Machingambi,2023-08-28,"""My English teacher ignores me if I complain t...",[Zimbabwe],[right to education]

## 6- saving the dictionnary with places names

In [12]:
with open("place_country.json", "w", encoding="utf-8") as f:
    json.dump(new_map_dic, f)

In [13]:
new_map_dic

{'Kinshasa': 'République démocratique du Congo',
 'Kagera': 'Tanzania',
 'Dar es Salaam': 'Tanzania',
 'United Republic of Tanzania': 'Tanzania',
 'Tanzania': 'Tanzania',
 'Middleburg': 'United States',
 'South Africa': 'South Africa',
 'Mthwalo Village': None,
 'Zambia': 'Zambia',
 'XX': 'Suomi / Finland',
 'Kanyama': 'République démocratique du Congo',
 'Kalundu': 'République démocratique du Congo',
 'Lusaka': 'Zambia',
 'Kalumbu Village': 'Malawi',
 'West Area': 'United States',
 'Mandevu Township': None,
 'Jafureya village': None,
 'Eastern Province': 'Sri Lanka',
 'Makule': 'United States',
 'Lundazi': 'Zambia',
 'Chikwa': 'Zambia',
 'Chama': 'United States',
 'Muchinga Province': 'Zambia',
 'MC': 'Monaco',
 'Nyimba': 'Zambia',
 'the Copperbelt Province': 'Zambia',
 'Chipata': 'Zambia',
 'Western Province': 'Sri Lanka',
 'Chibanda Village': 'Malawi',
 'Chasefu': 'Zambia',
 'Mpulungu': 'Zambia',
 'Northern Province': 'Sri Lanka',
 'Mukushi': None,
 'Central Province': 'Sri Lanka',
 'Mongu': 'Zambia',
 'Kalomo': 'Zambia',
 'Southern Province': 'Sri Lanka',
 'Nkungulu': 'Tanzania',
 'Katete': 'Zambia',
 'Kamphanda village': None,
 'Mtete': 'Moçambique',
 'MM': 'မြန်မာ',
 'Mozambique': 'Moçambique',
 'DC': 'Colombia',
 'Nsakambewa': None,
 'Dowa District': 'Sri Lanka',
 'Maere Village': 'Norge',
 'Nsanje District': 'Zambia',
 'Goma': 'République démocratique du Congo',
 'Gboko': 'Nigeria',
 'Nigeria': 'Nigeria',
 'Uganda': 'Uganda',
 'Landmark': '中国',
 'Amanase-Boketey': None,
 'Suhum': 'Ghana',
 'South Africa’s': 'South Africa',
 'Emalahleni': 'South Africa',
 'NAMIBIA': 'Namibia',
 'Eenhana': 'Namibia',
 'San community': 'Philippines',
 'Ghana': 'Ghana',
 'Kenya': 'Kenya',
 'the United Republic of Tanzania': 'Tanzania',
 'Balama': 'Moçambique',
 'Quissanga': 'Moçambique',
 'Mueda': 'Moçambique',
 'Benga': 'România',
 'Zambezia': 'Moçambique',
 'Nampula': 'Moçambique',
 'Lichinga': 'Moçambique',
 'Niassa province': 'Moçambique',
 'medo': 'United States',
 'Pessoas': 'Brasil',
 'Angola': 'Angola',
 'Benin': 'Bénin',
 'Rukiga District': 'Rwanda',
 'Empangeni': 'South Africa',
 'Kasama': 'Zambia',
 'Rutana province': 'Burundi',
 'Burundi': 'Burundi',
 'Rwanda': 'Rwanda',
 'Bulawayo': 'Zimbabwe',
 'Cameroon': 'Cameroun',
 'sont': 'Danmark',
 'Muatize': None,
 'Mabotsa': 'South Africa',
 'Dogbo': 'Bénin',
 'A.A.': 'Tonga',
 'D.C.K.': 'Argentina',
 'Allada': 'Bénin',
 'G.M.': 'United States',
 'Gaborone': 'Botswana',
 'Gaoua': 'Burkina Faso',
 'Nairobi': 'Kenya',
 'Bujumbura': 'Burundi',
 'Busoni': 'Burundi',
 'Kirundo': 'Burundi',
 'Muyange': 'Burundi',
 'Northern Burundi': None,
 'Bafoussam': 'Cameroun',
 'France': 'France',
 'B.M.': 'France',
 'Yaounde': 'Cameroun',
 'J.K.': 'Brasil',
 'Chambombo': 'République démocratique du Congo',
 'South Kivu': 'République démocratique du Congo',
 'Bukavu': 'République démocratique du Congo',
 'Lubunga': 'République démocratique du Congo',
 'Egypt': 'مصر',
 'New Zealand': 'New Zealand / Aotearoa',
 'Gabon': 'Gabon',
 'K.Y.': 'ประเทศไทย',
 'Owoakra': None,
 'Boketey': None,
 'Matam': 'Sénégal',
 'Conakry': 'Guinée',
 'Guinea': 'Guinée',
 'Damankania': None,
 'Gunasua': 'Ghana',
 'Tunisia': 'تونس',
 'E.J.': '日本',
 'Vihiga County': 'Kenya',
 'Embu': 'Brasil',
 'T.T.': 'België / Belgique / Belgien',
 'Lesotho': 'Lesotho',
 'Vohikely': None,
 'Madagascar': 'Madagasikara / Madagascar',
 'Bongolava': 'Madagasikara / Madagascar',
 'P.S.': 'Nederland',
 'Chiradzulu': 'Malawi',
 'Mombe Village': None,
 'Richard Village': 'Liberia',
 'M.Z.': 'België / Belgique / Belgien',
 'Dowa': 'Malawi',
 'D.D.': 'România',
 'Fana': 'Italia',
 'Goloninia': None,
 'Bamako': 'Mali',
 'Mali': 'Mali',
 'P.A.': 'Sierra Leone',
 'Macharote': 'Moçambique',
 'Mkhome': None,
 'the Angonia District': None,
 'Tete Province': 'Moçambique',
 'A.S.': 'Deutschland',
 'Uukwiyuwuushona Village': None,
 'Namibia': 'Namibia',
 'Katutura': 'Namibia',
 'Dar es Salam': 'Tanzania',
 'Niamey': 'Niger',
 'Okuta': 'Uganda',
 'Onitsha': 'Nigeria',
 'Ilorin': 'Nigeria',
 'Nyamasheke': 'Rwanda',
 'N.C': 'United States',
 'Senegal': 'Sénégal',
 'Thies': 'Sénégal',
 'Mpumalanga': 'South Africa',
 'Nkoyoyo': 'Burundi',
 'Swaziland': 'Eswatini',
 'S.M.': 'Canada',
 'P.Z.': 'Liberia',
 'Lubombo': 'Eswatini',
 'Muleba District': 'Tanzania',
 'E.D.': 'United States',
 'Sengerema': 'Tanzania',
 'Bundala Luhende': None,
 'Kishapu District': 'Tanzania',
 'Mwanza': 'Tanzania',
 'P.E.': 'Argentina',
 'Ndamhi Village': 'Tanzania',
 'Mwanza Region': 'Tanzania',
 'Kilimanjaro Region': 'Tanzania',
 'N.M.': 'United States',
 'M.S.': 'Papua Niugini',
 'Nakonde District': 'Zambia',
 'Senanga District': 'Zambia',
 'Zimbabwe': 'Zimbabwe',
 'Chibanda': 'Malawi',
 'Interactive': 'Australia',
 'the Republic of Madagascar': 'United States',
 'Ikongo': 'Congo',
 'the Democratic Republic of Congo': 'United States',
 'Congo': 'République démocratique du Congo',
 'Democratic Republic of Congo': 'Zambia',
 'UK': 'United Kingdom',
 'BUKAVU District': 'Zambia',
 'SOUTH KIVU Province': None,
 'Ireland': 'Éire / Ireland',
 'Sinanya': 'Guinée',
 'Yabara, Guinea': 'Guinée',
 'C.A.K.': 'Polska',
 'Vihiga county': 'Kenya',
 'Mawawa Village': 'République démocratique du Congo',
 'Mitundu': 'Malawi',
 'Tezanga': None,
 'Chinomba Village': None,
 'Ribáuè': 'Moçambique',
 'Nampula Province': 'Moçambique',
 'Manica': 'Moçambique',
 'Moatize': 'Moçambique',
 'Oshikoto Region': 'Namibia',
 'Kwara State': 'Nigeria',
 'Anambra State': 'Nigeria',
 'Macuba': 'Rwanda',
 'USA': 'United States',
 'New York City': 'United States',
 'New York': 'United States',
 'Hlalanikahle Township -Witbank Mpumalanga': None,
 'M.N.': 'República Dominicana',
 'the Village of Bulamula': None,
 'Kagera Region': 'Tanzania',
 'Kasungumile Ward': None,
 'Sengerema District': 'Tanzania',
 'Mhunze Village': 'Tanzania',
 'Shinyanga Region': 'Tanzania',
 'Kwimba District': 'Papua Niugini',
 'Tanga': 'Tonga',
 'California': 'United States',
 'Dapaong': 'Togo',
 'Boston': 'United States',
 'Massachusetts': 'United States',
 'Katete District': 'Zambia',
 'Atlanta': 'United States',
 'Georgia': 'United States',
 'Josina': 'Italia',
 'Francois': 'France',
 'Bafousam': None,
 'Mbujimayi': 'République démocratique du Congo',
 'Ampatsakana': 'Madagasikara / Madagascar',
 'Gendarmerie': 'ⵍⵣⵣⴰⵢⴻⵔ الجزائر',
 'the Blantyre District': 'Zambia',
 'Blantyre': 'Malawi',
 'Kawinga village': 'Malawi',
 'Machinga District': 'Malawi',
 'Sitima': 'Malawi',
 'Lilongwe': 'Malawi',
 'Djeneba': 'Mali',
 'Mlungu': 'Tanzania',
 'Usadala': None,
 'Utemini': 'Tanzania',
 'Uyui District': 'Tanzania',
 'Shinyanga': 'Tanzania',
 'Togo': 'Togo',
 'West Africa': 'France',
 'Yamene': 'Liberia',
 'Thembi': 'South Africa',
 'Mbizi Village': 'Moçambique',
 'Mega Ward': 'South Africa',
 'Kahama District': 'Côte d’Ivoire',
 'the Lake Victoria Region': 'Philippines',
 'Angyo': '日本',
 'Buruku LGA': None,
 'Benue State': 'Nigeria',
 'Kwaggafontein Village': None,
 'Mustapha': 'France',
 'Banjul': 'Gambia',
 'Garu': 'India',
 'Kumasi': 'Ghana',
 'Sapala': 'Burkina Faso',
 'Fanta': 'Djibouti جيبوتي',
 'zona': 'United States',
 'KENYA': 'Kenya',
 'Nyeri': 'Kenya',
 'Nyeri County': 'Kenya',
 'Gavudunyi village': None,
 'Jamenya': None,
 'Ouagadougou': 'Burkina Faso',
 'Burkina Faso': 'Burkina Faso',
 'Kitale': 'Kenya',
 'Rift Valley Province': 'Zambia',
 'Thaba-Tseka': 'Lesotho',
 'Liberia': 'Liberia',
 'D.N.J.R.': None,
 'Antanamivony': 'Madagasikara / Madagascar',
 'Mchinji': 'Malawi',
 'Phalombe District': None,
 'Nakawa': 'Uganda',
 'Malian Empire': None,
 'Dar Naim': 'Mauritanie موريتانيا',
 'Zambézia': 'Moçambique',
 'South-South Nigeria': 'Nigeria',
 'Rutsiro District of Western Province': None,
 'Masonry': 'United States',
 'Rutsiro District': 'Rwanda',
 'Musanze': 'Rwanda',
 'Sénégal': 'Sénégal',
 'La': 'ປະເທດລາວ',
 'Sierra Leone': 'Sierra Leone',
 'Somalia': 'Soomaaliya الصومال',
 'Dadaab': 'Kenya',
 'South Sudan': 'South Sudan جنوب السودان',
 'Hon Mwaura’s': None,
 'Nathan': 'Australia',
 'Geita': 'Tanzania',
 'Nakatogo': 'Uganda',
 'Kyotera': 'Uganda',
 'Nakatogo Village': 'Uganda',
 'Kampala': 'Uganda',
 'Abdul': 'Malaysia',
 'Salaama': 'Uganda',
 'Lusaka Kalundu Township': None,
 'Mwandi District': 'Zambia',
 'Kalomo District': 'Zambia',
 'the District of Katete': None,
 'Chanida': 'پاکستان',
 'Chadiza': 'Zambia',
 'Mutupa': 'Zambia',
 'Matero': 'Perú',
 'Anele': 'Argentina',
 'Morrumbala': 'Moçambique',
 'Laston Chipiliro': None,
 'Maguba': 'Brasil',
 'Saiti Kadzuwa Village': None,
 'zeru': 'Hrvatska'}